apiVersion: v1
description: Seldon Core helm chart for Kubernetes on AWS
keywords:
- kubernetes
- machine-learning
name: seldon-core-aws
sources:
- https://github.com/SeldonIO/seldon-core-aws
version: 0.5.0
