ambassador:
  enabled: true
  singleNamespace: false
certManager:
  enabled: false
engine:
  grpc:
    port: 5001
  image:
    pullPolicy: IfNotPresent
    registry: 403495124976.dkr.ecr.us-east-1.amazonaws.com/cc92bd08-3aee-4006-983a-b74fbf1cbfa8/cg-2585947346
    repository: seldonio/engine
    tag: 0.5.0-latest
  logMessagesExternally: false
  port: 8000
  prometheus:
    path: prometheus
  securityContext:
    enabled: true
  serviceAccount:
    name: default
  user: 8888
image:
  pullPolicy: Always
  registry: 403495124976.dkr.ecr.us-east-1.amazonaws.com/cc92bd08-3aee-4006-983a-b74fbf1cbfa8/cg-2585947346
  repository: seldonio/seldon-core-operator
  tag: 0.5.0-latest
istio:
  enabled: false
  gateway: seldon-gateway
predictiveUnit:
  port: 9000
rbac:
  configmap:
    create: true
  create: true
serviceAccount:
  create: true
  name: seldon-manager
usageMetrics:
  enabled: true
webhook:
  port: 443
